WIP cleaning up new SalesReport entries
error: TypeError: __init__() takes 1 positional argument but 13 were given
LogIn issue from earlier was due to use of wrong username at login